import { TeamRepository } from "../repositories/team.repository";
import { Team, CreateTeamDto, UpdateTeamDto } from "../types";
import { ConflictError, NotFoundError } from "../utils/errors";
import { getCurrentDateTime } from "../utils/date";

export class TeamService {
  private teamRepository: TeamRepository;

  constructor() {
    this.teamRepository = new TeamRepository();
  }

  async getAllTeams(): Promise<Team[]> {
    return this.teamRepository.findAll();
  }

  async getTeamById(id: string): Promise<Team> {
    const team = await this.teamRepository.findById(id);
    if (!team) {
      throw new NotFoundError("Team");
    }
    return team;
  }

  async createTeam(teamData: CreateTeamDto): Promise<Team> {
    // Check if team name already exists (only if name is provided)
    if (teamData.name) {
      const existingTeam = await this.teamRepository.findByName(
        String(teamData.name || "").trim()
      );
      if (existingTeam) {
        throw new ConflictError("Team name already exists");
      }
    }

    const newTeam: Team = {
      id: "", // Will be generated by Firebase
      name: String(teamData.name || "").trim(),
      description: teamData.description ? String(teamData.description).trim() : "",
      createdAt: getCurrentDateTime(),
      updatedAt: getCurrentDateTime(),
    };

    const createdTeam = await this.teamRepository.create(newTeam);
    return createdTeam;
  }

  async updateTeam(id: string, teamData: UpdateTeamDto): Promise<Team> {
    const existingTeam = await this.teamRepository.findById(id);
    if (!existingTeam) {
      throw new NotFoundError("Team");
    }

    // If name is being updated, check if it's already taken
    if (teamData.name && teamData.name !== existingTeam.name) {
      const existingName = await this.teamRepository.findByName(
        String(teamData.name || "").trim()
      );
      if (existingName) {
        throw new ConflictError("Team name already exists");
      }
    }

    const updateData: any = {};
    if (teamData.name !== undefined) updateData.name = String(teamData.name || "").trim();
    if (teamData.description !== undefined) updateData.description = teamData.description ? String(teamData.description).trim() : "";

    const updatedTeam = await this.teamRepository.update(id, updateData);
    return updatedTeam;
  }

  async deleteTeam(id: string): Promise<void> {
    const existingTeam = await this.teamRepository.findById(id);
    if (!existingTeam) {
      throw new NotFoundError("Team");
    }

    await this.teamRepository.delete(id);
  }
}

